# Generated by Django 4.2.11 on 2024-03-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0002_community_owner_alter_community_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='isPublic',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='reputationRating',
            new_name='reputation_rating',
        ),
    ]
