# Generated by Django 4.2.11 on 2024-04-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='owner',
        ),
        migrations.AddField(
            model_name='community',
            name='owner_id',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='communiche.user'),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
