# Generated by Django 4.2.11 on 2024-04-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0005_remove_community_owner_community_owner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
