# Generated by Django 4.2.11 on 2024-04-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0007_alter_community_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='communiche.user'),
        ),
    ]
