# Generated by Django 4.2.11 on 2024-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0009_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
    ]
