# Generated by Django 4.2.11 on 2024-04-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0010_datafield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataField',
            new_name='DataFields',
        ),
    ]
