# Generated by Django 4.2.11 on 2024-04-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0013_auto_20240406_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafields',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('geo', 'Geolocation'), ('number', 'Number'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('link', 'Link'), ('list', 'List'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('dropdown', 'Dropdown'), ('rating', 'Rating'), ('slider', 'Slider'), ('range', 'Range'), ('color', 'Color'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL'), ('html', 'HTML'), ('markdown', 'Markdown'), ('json', 'JSON'), ('xml', 'XML'), ('yaml', 'YAML'), ('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('word', 'Word'), ('powerpoint', 'PowerPoint'), ('code', 'Code'), ('formula', 'Formula'), ('math', 'Math'), ('currency', 'Currency'), ('percent', 'Percent'), ('unit', 'Unit'), ('duration', 'Duration'), ('timezone', 'Timezone'), ('language', 'Language'), ('country', 'Country'), ('currency', 'Currency'), ('emoji', 'Emoji'), ('flag', 'Flag')], default='text', max_length=200),
        ),
    ]
