# Generated by Django 4.2.11 on 2024-04-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0014_alter_datafields_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafields',
            name='template',
        ),
        migrations.RemoveField(
            model_name='template',
            name='community',
        ),
        migrations.AddField(
            model_name='template',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='communiche.datafields'),
        ),
    ]
