# Generated by Django 4.2.11 on 2024-04-10 05:28

from django.db import migrations

def create_default_template(apps, schema_editor):
    Template = apps.get_model('communiche', 'Template')
    Template.objects.create(name='Default', description='Default template for all communities')
    

class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0015_remove_datafields_template_remove_template_community_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_template),
    ]
