# Generated by Django 4.2.11 on 2024-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0016_auto_20240410_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='field_label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
