# Generated by Django 4.2.11 on 2024-04-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0017_template_field_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='field',
        ),
        migrations.RemoveField(
            model_name='template',
            name='field_label',
        ),
        migrations.AddField(
            model_name='template',
            name='fields',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='DataFields',
        ),
    ]
