# Generated by Django 4.2.11 on 2024-04-12 08:39

from django.db import migrations

def create_default_template(apps, schema_editor):
    Template = apps.get_model('communiche', 'Template')
    
    Template.objects.create(
        name='Default Template',
        description='Default template for all communities.',
        fields=[
            {'field_name': 'title', 'field_type': 'text'},
            {'field_name': 'description', 'field_type': 'text'},
            {'field_name': 'image', 'field_type': 'image'}
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0018_remove_template_field_remove_template_field_label_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_template),
    ]
