# Generated by Django 3.2.8 on 2024-04-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0021_auto_20240414_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.community')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.template')),
            ],
        ),
    ]
