# Generated by Django 3.2.8 on 2024-04-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0022_templatecommunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.user')),
            ],
        ),
    ]
