# Generated by Django 3.2.8 on 2024-04-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0023_communityuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', through='communiche.CommunityUser', to='communiche.User'),
        ),
    ]
