# Generated by Django 3.2.8 on 2024-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0025_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuser',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
