# Generated by Django 3.2.8 on 2024-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0027_joinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
