# Generated by Django 3.2.8 on 2024-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0029_auto_20240428_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to='communiche.User'),
        ),
    ]
