# Generated by Django 3.2.8 on 2024-05-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0031_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.user')),
            ],
        ),
    ]
