# Generated by Django 3.2.8 on 2024-05-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0033_alter_pcomment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
    ]
