# Generated by Django 5.0.4 on 2024-11-15 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0035_alter_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='communiche.label')),
            ],
        ),
    ]
