# Generated by Django 3.2.8 on 2024-11-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0035_alter_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='communiche.Tag'),
        ),
    ]
