# Generated by Django 3.2.8 on 2024-11-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0035_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='communiche.Tag'),
        ),
    ]
