# Generated by Django 3.2.8 on 2024-11-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0035_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communiche.template'),
        ),
    ]
