# Generated by Django 3.2.8 on 2024-11-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0037_alter_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
    ]
