# Generated by Django 3.2.8 on 2024-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0037_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/icons/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
