# Generated by Django 3.2.8 on 2024-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0038_auto_20241112_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
