# Generated by Django 3.2.8 on 2024-11-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0036_auto_20241119_1245'),
        ('communiche', '0039_report_status'),
    ]

    operations = [
    ]
