# Generated by Django 3.2.8 on 2024-11-24 06:26

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0039_alter_badge_id'),  # Replace with the actual previous migration file
    ]