# Generated by Django 3.2.8 on 2024-11-24 06:26

from django.db import migrations

def create_badges(apps, schema_editor):
    Badge = apps.get_model('communiche', 'Badge')
    
    Badge.objects.create(
        name="Contributor",
        description="Awarded for posting 5 posts.",
        tier="Bronze",
        criteria={"posts_count": 5}
    )

    Badge.objects.create(
        name="Influencer",
        description="Awarded for liking 10 posts.",
        tier="Silver",
        criteria={"likes_given": 10}
    )

    Badge.objects.create(
        name="Veteran",
        description="Awarded for being a member of a community for 15 days.",
        tier="Gold",
        criteria={"membership_duration_days": 15}
    )

    Badge.objects.create(
        name="Community Leader",
        description="Awarded for being a community moderator.",
        tier="Gold",
        criteria={"is_moderator": True}
    )

    Badge.objects.create(
        name="Popular Post",
        description="Awarded for having a post liked more than 20 times.",
        tier="Gold",
        criteria={"single_post_likes": 20}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0039_alter_badge_id'),  # Replace with the actual previous migration file
    ]

    operations = [
        migrations.RunPython(create_badges),
    ]
