# Generated by Django 5.0.4 on 2024-11-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0036_auto_20241119_1245'),
        ('communiche', '0039_report_status'),
    ]

    operations = [
    ]
