# Generated by Django 5.0.4 on 2024-11-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0040_merge_0036_auto_20241119_1245_0039_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(related_name='communities', to='communiche.tag'),
        ),
    ]
