# Generated by Django 3.2.8 on 2024-11-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0036_auto_20241112_1238'),
        ('communiche', '0039_report_status'),
        ('communiche', '0041_auto_20241124_1005'),
    ]

    operations = [
    ]
