# Generated by Django 3.2.8 on 2024-11-24 09:36

from django.db import migrations

def create_tags(apps, schema_editor):
    Tag = apps.get_model('communiche', 'Tag')
    
    tags = [
        "Technology", "Science", "Health", "Education", "Business", "Travel", "Food", "Lifestyle", 
        "Celebrities", "Finance", "History", "Gaming", "Movies", "Music", "Photography", "Books", 
        "Art", "Crafts", "Sports", "Fitness", "Fashion", "Politics", "Economy", "Climate", 
        "Local News", "Global News", "Announcement", "Event", "Poll", "Review", "Entertainment", 
        "Tips", "Feedback", "Help Needed", "Q&A", "Success Story", "Debate"
    ]
    
    for tag in tags:
        if not Tag.objects.filter(name=tag).exists():
            Tag.objects.create(name=tag)

class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0042_merge_20241124_1134'),
    ]

    operations = [
        migrations.RunPython(create_tags),
    ]