# Generated by Django 3.2.8 on 2024-11-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0042_merge_20241124_1138'),
        ('communiche', '0042_merge_20241124_1203'),
        ('communiche', '0043_auto_20241124_1250'),
    ]

    operations = [
    ]