# Generated by Django 5.0.4 on 2024-11-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0040_merge_0036_auto_20241119_1245_0039_report_status'),
        ('communiche', '0044_merge_20241124_1613'),
    ]

    operations = [
    ]
