# Generated by Django 3.2.8 on 2024-12-03 17:49

from django.db import migrations, models, connection
from datetime import datetime

def create_badges(apps, schema_editor):
    Badge = apps.get_model('communiche', 'Badge')

    badges = [
        (1, "Contributor", "Created 10 Posts", "Bronze", {"posts_count": 1}, "badges/contributor.png"),
        (2, "Contributor", "Created 50 Posts", "Silver", {"posts_count": 5}, "badges/contributor.png"),
        (3, "Contributor", "Created 100 Posts", "Gold", {"posts_count": 10}, "badges/contributor.png"),
        (4, "Commentator", "Made 10 Comments", "Bronze", {"comments_count": 1}, "badges/commentator.png"),
        (5, "Commentator", "Made 50 Comments", "Silver", {"comments_count": 5}, "badges/commentator.png"),
        (6, "Commentator", "Made 100 Comments", "Gold", {"comments_count": 10}, "badges/commentator.png"),
        (7, "Conversation Starter", "One of Your Posts Received 10 Comments", "Bronze", {"single_post_comments": 1}, "badges/conversation_starter.png"),
        (8, "Conversation Starter", "One of Your Posts Received 50 Comments", "Silver", {"single_post_comments": 5}, "badges/conversation_starter.png"),
        (9, "Conversation Starter", "One of Your Posts Received 100 Comments", "Gold", {"single_post_comments": 10}, "badges/conversation_starter.png"),
        (10, "Look Mom I'm Famous", "One of Your Posts Received 10 Likes", "Bronze", {"single_post_likes": 1}, "badges/famous.png"),
        (11, "Look Mom I'm Famous", "One of Your Posts Received 50 Likes", "Silver", {"single_post_likes": 5}, "badges/famous.png"),
        (12, "Look Mom I'm Famous", "One of Your Posts Received 100 Likes", "Gold", {"single_post_likes": 10}, "badges/famous.png"),
        (13, "People Person", "Liked 10 Posts & Comments", "Bronze", {"likes_given": 1}, "badges/people.png"),
        (14, "People Person", "Liked 50 Posts & Comments", "Silver", {"likes_given": 5}, "badges/people.png"),
        (15, "People Person", "Liked 100 Posts & Comments", "Gold", {"likes_given": 10}, "badges/people.png"),
        (16, "Social Butterfly", "You Joined 10 Communities", "Bronze", {"communities_joined": 1}, "badges/social_butterfly.png"),
        (17, "Social Butterfly", "You Joined 25 Communities", "Silver", {"communities_joined": 5}, "badges/social_butterfly.png"),
        (18, "Social Butterfly", "You Joined 50 Communities", "Gold", {"communities_joined": 10}, "badges/social_butterfly.png"),
        (19, "Community Leader", "You Created 10 Communities", "Bronze", {"communities_created": 1}, "badges/community_leader.png"),
        (20, "Community Leader", "You Created 25 Communities", "Silver", {"communities_created": 5}, "badges/community_leader.png"),
        (21, "Community Leader", "You Created 50 Communities", "Gold", {"communities_created": 10}, "badges/community_leader.png"),
        (22, "Old But Gold", "Communiche User For 10 Days", "Bronze", {"membership_duration_days": 5}, "badges/gold.png"),
        (23, "Old But Gold", "Communiche User For 50 Days", "Silver", {"membership_duration_days": 10}, "badges/gold.png"),
        (24, "Old But Gold", "Communiche User For 100 Days", "Gold", {"membership_duration_days": 15}, "badges/gold.png"),
    ]

    for badge in badges:
        Badge.objects.update_or_create(
            id=badge[0],
            defaults={
                'name': badge[1],
                'description': badge[2],
                'tier': badge[3],
                'criteria': badge[4],
                'icon': badge[5]
            }
        )

def set_default_created_at(apps, schema_editor):
    User = apps.get_model('communiche', 'User')
    for user in User.objects.all():
        if user.created_at is None:
            user.created_at = datetime.now()
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0044_merge_20241124_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(
            create_badges
        ),
        migrations.RunPython(
            set_default_created_at
        ),
    ]