# Generated by Django 3.2.8 on 2024-12-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0044_merge_20241124_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
