# Generated by Django 3.2.8 on 2024-12-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0044_merge_20241124_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='communities', to='communiche.Badge'),
        ),
        migrations.CreateModel(
            name='CommunityBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.badge', db_constraint=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.community', db_constraint=False)),
            ],
            options={
                'db_table': 'communiche_communitybadge',
                'unique_together': {('community', 'badge')},
            },
        ),
    ]
