# Generated by Django 3.2.8 on 2024-12-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0044_merge_20241124_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='communities', to='communiche.Badge'),
        ),
    ]
