# Generated by Django 3.2.8 on 2024-12-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0045_badge_types_user_created_at'),
        ('communiche', '0045_community_rules'),
    ]

    operations = [
    ]
