# Generated by Django 3.2.8 on 2024-12-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0045_badge_types_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='communities', to='communiche.Tag'),
        ),
    ]
