# Generated by Django 3.2.8 on 2024-12-15 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0045_badge_types_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tier', models.CharField(max_length=20)),
                ('criteria', models.JSONField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/icons/')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.community')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunityBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.communitybadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communiche.user')),
            ],
        ),
    ]
