# Generated by Django 3.2.8 on 2024-11-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0045_merge_20241130_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(related_name='communities', to='communiche.Tag'),
        ),
    ]
