# Generated by Django 3.2.8 on 2024-11-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0045_merge_20241130_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='tags',
        ),
    ]
