# Generated by Django 3.2.8 on 2024-12-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0045_userinterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
