# Generated by Django 3.2.8 on 2024-12-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0046_communitybadge_usercommunitybadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitybadge',
            name='tier',
        ),
    ]
