# Generated by Django 3.2.8 on 2024-12-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0046_communitybadge_usercommunitybadge'),
        ('communiche', '0046_merge_20241215_1413'),
    ]

    operations = [
    ]
