# Generated by Django 3.2.8 on 2024-12-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0047_remove_communitybadge_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitybadge',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='communitybadge',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
