# Generated by Django 3.2.8 on 2024-12-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0046_community_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_wikidata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='qid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
