# Generated by Django 3.2.8 on 2024-12-19 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0047_merge_20241218_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_label', models.CharField(max_length=255)),
                ('qid', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, choices=[('user_interest', 'User Interest'), ('post', 'Post')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='usercommunitybadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='usercommunitybadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='communities', to='communiche.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='qid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CommunityBadge',
        ),
        migrations.DeleteModel(
            name='UserCommunityBadge',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='communiche.tag'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='communiche.user'),
        ),
        migrations.AddField(
            model_name='relatedentity',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_entities', to='communiche.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'tag')},
        ),
    ]
