# Generated by Django 3.2.8 on 2024-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0048_auto_20241215_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitybadge',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
