# Generated by Django 3.2.8 on 2024-12-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0048_auto_20241202_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_wikidata',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='qid',
        ),
    ]
