# Generated by Django 3.2.8 on 2024-12-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0049_alter_communitybadge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunitybadge',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communiche.community'),
            preserve_default=False,
        ),
    ]
