# Generated by Django 3.2.8 on 2024-12-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0046_merge_20241215_1413'),
        ('communiche', '0050_auto_20241213_1929'),
    ]

    operations = [
    ]
