# Generated by Django 3.2.8 on 2024-12-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communiche', '0050_usercommunitybadge_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommunitybadge',
            name='community',
        ),
    ]
